### ISSUE TITLE
SOme amalur art

### ISSUE THREAD

**Issue by MuffinProof** [thunderer/Amalur#1]
https://www.deviantart.com/gorrem/art/The-Long-Knives-of-Alyn-Shir-Assassination-334158697
![image](https://user-images.githubusercontent.com/70962765/92493093-02d04180-f1ec-11ea-8e81-0af83c38d9aa.png)

![image](https://user-images.githubusercontent.com/70962765/92493296-3f9c3880-f1ec-11ea-9e07-a674b39b1ce0.png)

https://www.deviantart.com/alphaprimesaviour/art/Dragon-Scale-Chakrams-734367297
![image](https://user-images.githubusercontent.com/70962765/92493335-4c209100-f1ec-11ea-9d06-5d44e203905f.png)

https://www.deviantart.com/synczoid/art/LineArt-Alyn-299763042
![image](https://user-images.githubusercontent.com/70962765/92493682-b5a09f80-f1ec-11ea-9f40-d6fabc8e5e78.png)

https://www.deviantart.com/gorrem/art/Amalur-Kollossae-336498013
![image](https://user-images.githubusercontent.com/70962765/92494027-19c36380-f1ed-11ea-8684-ef627d36fe51.png)

https://www.deviantart.com/isriana/art/Amalur-Fae-Speedpaintings-301419085
![image](https://user-images.githubusercontent.com/70962765/92494150-411a3080-f1ed-11ea-8850-b70dbb8a1dd2.png)

https://www.deviantart.com/thednightshade/art/Boggart-384061558
![image](https://user-images.githubusercontent.com/70962765/92494264-67d86700-f1ed-11ea-9d68-c0757dbf97c4.png)

https://www.deviantart.com/notesz/art/Crudok-620781035
![image](https://user-images.githubusercontent.com/70962765/92494359-88082600-f1ed-11ea-8900-0d375dbe29a6.png)

**Comment by thunderer** [comment]
Thanks! I just updated the `Art` section with all the links from this PR.
